[versions]

agp = "8.12.0"
androidx-activityCompose = "1.10.1"
androidx-uiTest = "1.8.3"
compose = "1.10.0-alpha02"
detekt = "1.23.8"
hotReload = "1.0.0-rc01"
koog = "0.5.0"
kotlin = "2.2.20"
ktlint = "1.7.1"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
