name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'zulu'
  LLM_TYPE: 'ollama_granite'

jobs:


  Lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew wrapper --gradle-version latest -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace
      - run: ./gradlew wrapper --gradle-version latest -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update Gradle wrapper

      - run: ./gradlew ktlintFormat -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Ktlint format

      - run: ./gradlew ciLint -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace



  Tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        gradle-tasks: [
          ":shared:sharedApp:jvmTest",
          # "testAndroid",
          # "testDebugUnitTest",
          ":shared:sharedApp:wasmJsBrowserTest"
        ]
        os: [ ubuntu-latest ]
        experimental: [ false ]
        emulator: [ false ]
        include:
          - gradle-tasks: "managedVirtualDeviceDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect"
            os: ubuntu-latest
            experimental: false
            emulator: true
          - gradle-tasks: "managedVirtualDeviceAndroidDeviceTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect"
            os: ubuntu-latest
            experimental: false
            emulator: true
          - gradle-tasks: "iosSimulatorArm64Test"
            os: macos-latest
            experimental: false
            emulator: false
    steps:

      - uses: actions/checkout@v5

      - name: Enable KVM group perms
        if: matrix.emulator
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew ciSdkManagerLicenses -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace
        if: matrix.emulator

      - run: ./gradlew clean ${{ matrix.gradle-tasks }} -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace

      - name: Get task name
        id: get_task
        run: echo "taskName=$(echo ${{ matrix.gradle-tasks }} | cut -d ' ' -f 1 | tr ':' '_')" >> $GITHUB_OUTPUT

      - name: Collect reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: reports-${{ steps.get_task.outputs.taskName }}-${{ matrix.os }}
          path: |
            **/build/reports/
          retention-days: 7



  Android:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew ciAndroid -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace



  Desktop:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew ciDesktop -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace



  WasmJsBrowser:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew ciWasmJsBrowser -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace

      - run: ./gradlew wasmJsBrowserDistribution -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace



  iOS:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v5

      - uses: gradle/actions/setup-gradle@v5

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: echo "LLM_TYPE=${{ env.LLM_TYPE }}" >> local.properties

      - run: ./gradlew ciIos -DLLM_TYPE=${{ env.LLM_TYPE }} --stacktrace
