name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'zulu'

jobs:


  Lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Gradle wrapper
